### ISSUE TITLE
Exact match search fails

### ISSUE THREAD

**Issue by adithewonderboy** [laravel-enso/filters#4]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Exact match search fails when a searchable integer column with 0 value is present inside table

### Steps to Reproduce
1. Make sure you have an integer column with value=0 inside table
![image](https://user-images.githubusercontent.com/58045802/102994223-58c0bf00-4527-11eb-999b-e0738b1219cf.png)

![image](https://user-images.githubusercontent.com/58045802/102994245-62e2bd80-4527-11eb-90f5-adda74c8e31a.png)

2. Search after any string ('example_search') with exact search mode on.
![image](https://user-images.githubusercontent.com/58045802/102994325-860d6d00-4527-11eb-902a-8108865e4107.png)

### Expected behavior
No results should come up if the string is not present inside data set

### Actual behavior
All the records that have status=0 (it can be another integer column=0) are displayed
![image](https://user-images.githubusercontent.com/58045802/102994383-a50bff00-4527-11eb-9496-68c01432d699.png)
This column is causing the issue:
![image](https://user-images.githubusercontent.com/58045802/102994500-d97fbb00-4527-11eb-8765-075a9f4a2338.png)

I think that mysql comparison is doing this because if we make a quick check we find out this condition to be true (normally false should be expected here):
![image](https://user-images.githubusercontent.com/58045802/102994590-0502a580-4528-11eb-8030-db9dbfeba722.png)

A suggested solution might be to replace 'Equal' operator with 'Like' inside Services\Search.php. This works for every case I tested
` $this->comparisonOperator = ComparisonOperators::Equal;` will be:
` $this->comparisonOperator = ComparisonOperators::Like;`

Please analyze this solution and share your thoughts  on this.
Thanks!

**Comment by robbykrlos** [comment]
Just a small comment here. This bug may also be a side effect of how MariaDB (in our situation) is handling strings to int conversions.

Just tested on WebSQL  (https://www.w3schools.com/sql/trysql.asp?filename=trysql_op_equal_to) and 
```sql
0 = "aaa"
```
**False**

Tried in MSSql, and here things are not possible due to casting errors. Casting has to be done manually, and "aa" will never cast to an Integer.

One more thing worth mentioning is that in MariaDB/MySql:
```sql
0 like "0" 
```
**True!**

Since LIKE operator is a pattern matching operator, may be type insensitive in some SQL languages which can in the end come with other side-effects.

**Comment by aocneanu** [comment]
Oh wow, I guess this is a nasty one.

If we use LIKE the comparison will be char by char if I'm correct, vs equal where the comparison is whole strings.
The main reason we have multiple search modes is to optimize search in really large tables, so replacing equal to like might beat this purpose.

We would have never found this case because we always use filters for statuses (enums) and interval filters for numbers. In other words there is no case where we would let an integer field searchable.

**Comment by adithewonderboy** [comment]
About the status being integer, I only use it as an example, we have some other integer fields, some counters inside our app that are searchable.
I understand your point that 'like' may impact your performance. We don't have big tables so for us the impact will be negligible.
Considering this, do you think you can make this operator customizable so we can set it differently? After a short look through the code, it's not easy for us to override locally with bind - all Search objects are instantiated with new..
Do you have any other ideas?
Thanks!

**Comment by robbykrlos** [comment]
Thank you! We'll have a look on it (cc7fa62).
